### ISSUE TITLE
some questions on release code?

### ISSUE THREAD

**Issue by zj19921221** [chail/patch-forensics#1]
hi I met a question when i read the script of "train.py"

In "train.py " of Line 3 "from models import create_model" there is no file named "create_model.py"?

Was you missed it ?

looking forward your reply!

**Comment by chail** [comment]
Hi, 

The function `create_model` is defined in `models/__init__.py` [(here)](https://github.com/chail/patch-forensics/blob/master/models/__init__.py#L31). It will choose whether to use the basic discriminator or patch discriminator based on the options you provide, and then within basic/patch discriminator it will initialize the discriminator architecture from the provided options.

I hope this helps!
