### ISSUE TITLE
The size of image patch on training and testing

### ISSUE THREAD

**Issue by chenshen03** [chail/patch-forensics#4]
Hi, thanks for your work!

How do you pre-process the input images in Patch Classifier during training and testing? Random crop to several patches per image, or use the full image as usual?

**Comment by chail** [comment]
The size of the patch using the Patch Classifier is determined using the receptive field of the classifiers (as the receptive field size is less than size of the full image). These patches are obtained by running the classifier in a fully convolutional manner over the full image as usual, so the output of the classifier is one prediction per patch of the input image.

**Comment by chenshen03** [comment]
Thank you very much!
